apiVersion: v1
kind: Namespace
metadata:
    name: tendermint-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tendermint-test
  name: validator-3
spec:
  selector:
    matchLabels:
      app: validator-3
  replicas: 1
  template:
    metadata:
      labels:
        app: validator-3
    spec:
      # nodeSelector:
      #   node1: node1  
      volumes:
      - name: node-volume 
        hostPath: 
          path: /Users/vjtc0n/Desktop/2018/Hyperledger/tendermint-starterkit/nodes-kubernetes/node3  
      containers:
      - name: validator-3
        image: vjtc0n/tendermint:latest
        volumeMounts:
        - mountPath: /tendermint
          name: node-volume
        workingDir: /tendermint
        ports:
          - containerPort: 46657
          - containerPort: 46656
        command: 
        - sh
        - "-c"
        - |
          tendermint node \
              --home ./
      - name: abci1
        image: vjtc0n/abci:latest
        command:
        - sh
        - "-c"
        - |
          abci-cli kvstore \
              --address=tcp://localhost:46658

---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-3
  namespace: tendermint-test
spec:
 selector:
   app: validator-3
 type: ClusterIP
 ports:
  - name: component
    protocol: TCP
    port: 46656
    targetPort: 46656     
