apiVersion: v1
kind: Namespace
metadata:
    name: tendermint-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tendermint-test
  name: validator-1
spec:
  selector:
    matchLabels:
      app: validator-1
  replicas: 1
  template:
    metadata:
      labels:
        app: validator-1
    spec:
      # nodeSelector:
      #   node1: node1  
      volumes:
      - name: node-volume 
        hostPath: 
          path: /Users/vjtc0n/Desktop/2018/Hyperledger/tendermint-starterkit/nodes-kubernetes/node1  
      containers:
      - name: validator-1
        image: vjtc0n/tendermint:latest
        volumeMounts:
        - mountPath: /tendermint
          name: node-volume
        workingDir: /tendermint
        ports:
          - containerPort: 46657
          - containerPort: 46656
          - containerPort: 26660
        command: 
        - sh
        - "-c"
        - |
          tendermint node \
              --home ./
      - name: abci1
        image: vjtc0n/abci:latest
        command:
        - sh
        - "-c"
        - |
          abci-cli dummy \
              --addr=tcp://localhost:46658

---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-1
  namespace: tendermint-test
spec:
 selector:
   app: validator-1
 type: ClusterIP
 ports:
  - name: component
    protocol: TCP
    port: 46656
    targetPort: 46656     

---
apiVersion: v1
kind: Service
metadata:
  name: tendermint-api
  namespace: tendermint-test
spec:
 selector:
   app: validator-1
 type: NodePort
 ports:
  - name: endpoint
    protocol: TCP
    port: 46657
    targetPort: 46657
    nodePort: 30657
  - name: metricendpoint
    protocol: TCP
    port: 26660
    targetPort: 26660
    nodePort: 31000
